/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.util.ArrayList;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.AbstractCellEditor;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

import classes.Receita;
import gerenciador.Gerenciador;

/**
 *
 * @author pedro
 */

class ButtonColumn extends AbstractCellEditor
        implements TableCellRenderer, TableCellEditor, ActionListener {
    JTable table;
    JButton renderButton;
    JButton editButton;
    String text;

    public ButtonColumn(JTable table, int column) {
        super();
        this.table = table;
        renderButton = new JButton();

        editButton = new JButton();
        editButton.setFocusPainted(false);
        editButton.addActionListener(this);

        TableColumnModel columnModel = table.getColumnModel();
        columnModel.getColumn(column).setCellRenderer(this);
        columnModel.getColumn(column).setCellEditor(this);
    }

    public Component getTableCellRendererComponent(
            JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        return renderButton;
    }

    public JButton getRenderButton() {
        return renderButton;
    }

    public Component getTableCellEditorComponent(
            JTable table, Object value, boolean isSelected, int row, int column) {
        text = (value == null) ? "" : value.toString();
        editButton.setText(text);
        return editButton;
    }

    public Object getCellEditorValue() {
        return text;
    }

    public void actionPerformed(ActionEvent e) {
        fireEditingStopped();
        System.out.println(e.getActionCommand() + " : " + table.getSelectedRow());
    }
}

public class Project extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Project() {
        initComponents();
        // Inicia Tabela de Receitas
        Gerenciador gerenciador = new Gerenciador();
        updateTabelaReceitas(gerenciador.readReceitas());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        Home = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        header = new javax.swing.JPanel();
        tituloHeader = new javax.swing.JLabel();
        sectionInteration = new javax.swing.JPanel();
        pesquisa = new javax.swing.JTextField();
        novo = new javax.swing.JButton();
        busca = new javax.swing.JButton();
        filtro = new javax.swing.JComboBox<>();

        jComboBox1.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Organizador de Receitas");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Home"); // NOI18N

        Home.setBackground(new java.awt.Color(255, 255, 255));
        Home.setMinimumSize(new java.awt.Dimension(200, 200));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[] {
                        "Titulo", "Tipo", "", ""
                }));
        jScrollPane1.setViewportView(tabela);
        tabela.setRowHeight(32);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(2).setPreferredWidth(32);
            tabela.getColumnModel().getColumn(2).setMaxWidth(32);
            tabela.getColumnModel().getColumn(3).setMaxWidth(32);
            tabela.getColumnModel().getColumn(3).setPreferredWidth(32);

            // Botões das Colunas
            editar = new ButtonColumn(tabela, 2);
            excluir = new ButtonColumn(tabela, 3);
            editar.getRenderButton().setIcon(new javax.swing.ImageIcon("./images/edit.png"));
            excluir.getRenderButton().setBackground(new Color(0xC80815));
            excluir.getRenderButton().setIcon(new javax.swing.ImageIcon("./images/delete.png"));
        }

        header.setBackground(new java.awt.Color(204, 0, 255));

        tituloHeader.setBackground(new java.awt.Color(255, 255, 255));
        tituloHeader.setFont(new java.awt.Font("Nimbus Roman", 0, 24)); // NOI18N
        tituloHeader.setForeground(new java.awt.Color(255, 255, 255));
        tituloHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloHeader.setText("Organizador de Receita");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
                headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerLayout.createSequentialGroup()
                                .addComponent(tituloHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 630,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        headerLayout.setVerticalGroup(
                headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tituloHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE));

        sectionInteration.setBackground(new java.awt.Color(255, 255, 255));

        pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaActionPerformed(evt);
            }
        });

        novo.setText("Novo");
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });

        busca.setBackground(new java.awt.Color(204, 0, 255));
        busca.setIcon(new javax.swing.ImageIcon("./images/big-search-len.png")); // NOI18N

        filtro.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout sectionInterationLayout = new javax.swing.GroupLayout(sectionInteration);
        sectionInteration.setLayout(sectionInterationLayout);
        sectionInterationLayout.setHorizontalGroup(
                sectionInterationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sectionInterationLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(novo)
                                .addGap(8, 8, 8)
                                .addComponent(busca, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 269,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 128,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        sectionInterationLayout.setVerticalGroup(
                sectionInterationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sectionInterationLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(sectionInterationLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(sectionInterationLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(filtro, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(novo, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(busca, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)));

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
                HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(header, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addComponent(sectionInteration, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1));
        HomeLayout.setVerticalGroup(
                HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(sectionInteration, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361,
                                        Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateTabelaReceitas(ArrayList<Receita> receitas) {
        DefaultTableModel tabelaReceitas = (DefaultTableModel) tabela.getModel();
        int i;
        for (i = tabelaReceitas.getRowCount() - 1; i >= 0; i--)
            tabelaReceitas.removeRow(i);
        for (i = 0; i < receitas.size(); i++)
            tabelaReceitas.addRow(new Object[] {
                    receitas.get(i).getTitulo(),
                    receitas.get(i).getTipo().getDescricao()
            });
    }

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_novoActionPerformed
        // TODO add your handling code here:
        new TelaNovaReceita().setVisible(true);

    }// GEN-LAST:event_novoActionPerformed

    private void pesquisaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pesquisaActionPerformed
        Gerenciador gerenciador = new Gerenciador();
        String nome = pesquisa.getText();
        updateTabelaReceitas(gerenciador.readReceitas(nome));
    }// GEN-LAST:event_pesquisaActionPerformed

    private void filtrosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_filtrosActionPerformed
        // TODO add your handling code here:
        pesquisa.setText("TESTE");
    }// GEN-LAST:event_filtrosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home;
    private javax.swing.JButton busca;
    private javax.swing.JComboBox<String> filtro;
    private javax.swing.JPanel header;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton novo;
    private javax.swing.JTextField pesquisa;
    private javax.swing.JPanel sectionInteration;
    private javax.swing.JTable tabela;
    private javax.swing.JLabel tituloHeader;
    private ButtonColumn editar;
    private ButtonColumn excluir;
    // End of variables declaration//GEN-END:variables
}
