/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.text.Normalizer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.function.Consumer;
import java.util.stream.Collectors;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import classes.Ingrediente;
import classes.Receita;
import enuns.TipoReceita;
import enuns.TipoUnidadeMedida;
import gerenciador.Gerenciador;

/**
 *
 * @author pedro
 */
public class TelaNovaReceita extends javax.swing.JFrame {

    /**
     * Creates new form TelaNovaReceita
     */
    public TelaNovaReceita(Consumer<ArrayList<Receita>> callback) {
        this.callback = callback;
        this.receitaId = -1;
        initComponents();
    }

    public TelaNovaReceita(Consumer<ArrayList<Receita>> callback, int receitaId) {
        this.callback = callback;
        this.receitaId = receitaId;
        initComponents();
        titulo.setText(gerenciador.getReceitaById(receitaId).getTitulo());
        for (Ingrediente ingrediente : gerenciador.getReceitaById(receitaId).getListaIngredientes())
            tabelaIngredientes.addRow(new Object[] {
                    ingrediente.getNome(),
                    ingrediente.getQuantidade(),
                    ingrediente.getTipoMedida().getDescricao(),
            });
        tipoReceita.setSelectedIndex(
                Arrays.asList(TipoReceita.values()).indexOf(gerenciador.getReceitaById(receitaId).getTipo()));
        modoDePreparo.setText(gerenciador.getReceitaById(receitaId).getModoDePreparo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        painelCrudReceita = new javax.swing.JPanel();
        titulo = new javax.swing.JTextField();
        tipoReceita = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeIngrediente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        quantidadeIngrediente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tipoIngrediente = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        modoDePreparo = new javax.swing.JTextArea();
        salvar = new javax.swing.JButton();
        gerenciador = new Gerenciador();

        setTitle("Receita");

        tipoReceita.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Vegetariana", "Massas", "Doces", "Carnes",
                        "Sobremesas", "Jantar", "Almoço", "Café da Manhã", "Vegana" }));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[] {
                        "Nome", "Quantidade", "Unidade de Medida", "Ações"
                }) {
            Class[] types = new Class[] {
                    java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabelaIngredientes = (DefaultTableModel) tabela.getModel();
            tabela.setRowHeight(26);
            tabela.getColumnModel().getColumn(3).setMinWidth(60);
            tabela.getColumnModel().getColumn(3).setPreferredWidth(60);
            tabela.getColumnModel().getColumn(3).setMaxWidth(60);
            excluir = new ButtonColumn(tabela, 3) {
                @Override
                public void actionPerformed(ActionEvent e) {
                    fireEditingStopped();
                    tabelaIngredientes.removeRow(tabela.getSelectedRow());
                }
            };
            excluir.getRenderButton().setBackground(new Color(0xC80815));
            excluir.getRenderButton().setIcon(new javax.swing.ImageIcon("./images/delete.png"));
        }

        jLabel1.setText("Titulo:");

        jLabel2.setText("Tipo da Receita:");

        jLabel3.setText("Ingrediente:");

        jLabel4.setText("Quantidade:");

        add.setBackground(new java.awt.Color(204, 0, 255));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jLabel5.setText("Unidade de Medida:");

        tipoIngrediente.setModel(
                new javax.swing.DefaultComboBoxModel<>(
                        new String[] { "Colher de sopa", "Colher de chá", "Gramas", "Unidade", "Xicara" }));

        jLabel6.setText("Modo de Preparo:");

        modoDePreparo.setColumns(20);
        modoDePreparo.setRows(5);
        jScrollPane1.setViewportView(modoDePreparo);

        salvar.setBackground(new java.awt.Color(0, 204, 51));
        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCrudReceitaLayout = new javax.swing.GroupLayout(painelCrudReceita);
        painelCrudReceita.setLayout(painelCrudReceitaLayout);
        painelCrudReceitaLayout.setHorizontalGroup(
                painelCrudReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelCrudReceitaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(painelCrudReceitaLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(painelCrudReceitaLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(painelCrudReceitaLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                516, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(tipoReceita,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 130,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(painelCrudReceitaLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(painelCrudReceitaLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(painelCrudReceitaLayout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCrudReceitaLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(painelCrudReceitaLayout.createSequentialGroup()
                                                        .addGap(2, 2, 2)
                                                        .addComponent(jScrollPane1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 443,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(salvar))
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(painelCrudReceitaLayout.createSequentialGroup()
                                                        .addGroup(painelCrudReceitaLayout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel3)
                                                                .addComponent(nomeIngrediente,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 194,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(19, 19, 19)
                                                        .addGroup(painelCrudReceitaLayout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                .addComponent(jLabel4,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(quantidadeIngrediente))
                                                        .addGap(74, 74, 74)
                                                        .addGroup(painelCrudReceitaLayout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel5,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(painelCrudReceitaLayout
                                                                        .createSequentialGroup()
                                                                        .addComponent(tipoIngrediente,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                138,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(30, 30, 30)
                                                                        .addComponent(add,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                65,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))))));
        painelCrudReceitaLayout.setVerticalGroup(
                painelCrudReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelCrudReceitaLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipoReceita, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(painelCrudReceitaLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelCrudReceitaLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tipoIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(quantidadeIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nomeIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(painelCrudReceitaLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(painelCrudReceitaLayout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(salvar))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 7, Short.MAX_VALUE)
                                .addComponent(painelCrudReceita, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 12, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(painelCrudReceita, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {
        boolean jaExisteIngrediente = false;
        for (int i = 0; i < tabelaIngredientes.getRowCount(); i++)
            if (gerenciador.normalizarString(String.valueOf(tabelaIngredientes.getValueAt(i, 0)))
                    .equals(gerenciador.normalizarString(nomeIngrediente.getText())))
                jaExisteIngrediente = true;
        if (jaExisteIngrediente || nomeIngrediente.getText().length() == 0)
            JOptionPane.showMessageDialog(new JFrame(),
                    "Adicione um nome ao ingrediente ou verifique se já não há este ingrediente.");
        else if (quantidadeIngrediente.getText().length() == 0)
            JOptionPane.showMessageDialog(new JFrame(),
                    "Digite a quantidade do ingrediente.");
        else {
            tabelaIngredientes.addRow(new Object[] {
                    nomeIngrediente.getText(),
                    quantidadeIngrediente.getText(),
                    tipoIngrediente.getSelectedItem(),
            });
            nomeIngrediente.setText("");
            quantidadeIngrediente.setText("");
            tipoIngrediente.setSelectedIndex(0);
        }
    }

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_salvarActionPerformed
        if (!(gerenciador.readReceitas().stream()
                .filter(receita -> gerenciador.normalizarString(receita.getTitulo())
                        .equals(gerenciador.normalizarString(titulo.getText())))
                .collect(Collectors.toList()).size() == 0
                || (receitaId != -1
                        && gerenciador.normalizarString(gerenciador.getReceitaById(receitaId).getTitulo())
                                .equals(gerenciador.normalizarString(titulo.getText()))))
                || titulo.getText().length() == 0)
            JOptionPane.showMessageDialog(new JFrame(),
                    "Adicione um título ou verifique se já não há receita com este título.");
        else if (tabelaIngredientes.getRowCount() == 0)
            JOptionPane.showMessageDialog(new JFrame(), "Adicione pelo menos um ingrediente.");
        else {
            if (receitaId != -1)
                gerenciador.delete(receitaId);
            salvarReceita();
            setVisible(false);
        }
    }// GEN-LAST:event_salvarActionPerformed

    private void salvarReceita() {
        gerenciador.add(
                String.valueOf(titulo.getText()), TipoReceita.values()[tipoReceita.getSelectedIndex()]);
        for (int i = 0; i < tabela.getRowCount(); i++)
            gerenciador.addIngrediente(String.valueOf(tabela.getValueAt(i, 0)),
                    TipoUnidadeMedida.valueOf(
                            Normalizer.normalize(
                                    String.valueOf(tabela.getValueAt(i, 2))
                                            .replaceAll(" ", "_").toUpperCase(),
                                    Normalizer.Form.NFD).replaceAll("[^\\p{ASCII}]", "")),
                    String.valueOf(tabela.getValueAt(i, 1)));
        gerenciador.addModoDePreparo(modoDePreparo.getText());
        gerenciador.salvarArmazenamento();
        callback.accept(gerenciador.readReceitas());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabela;
    private javax.swing.JTextArea modoDePreparo;
    private javax.swing.JTextField nomeIngrediente;
    private javax.swing.JPanel painelCrudReceita;
    private javax.swing.JTextField quantidadeIngrediente;
    private javax.swing.JButton salvar;
    private javax.swing.JComboBox<String> tipoIngrediente;
    private javax.swing.JComboBox<String> tipoReceita;
    private javax.swing.JTextField titulo;
    private ButtonColumn excluir;
    private Consumer<ArrayList<Receita>> callback;
    private Gerenciador gerenciador;
    private DefaultTableModel tabelaIngredientes;
    private int receitaId;

    // End of variables declaration//GEN-END:variables
}
