/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpb.poo.gui;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.stream.Collectors;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import br.edu.ifpb.poo.classes.Receita;
import br.edu.ifpb.poo.enuns.TipoReceita;
import br.edu.ifpb.poo.gerenciador.Gerenciador;

/**
 *
 * @author pedro
 */

public class Project extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Project() {
        gerenciador = new Gerenciador();
        initComponents();
        // Inicia Tabela de Receitas
        updateTabelaReceitas(gerenciador.readReceitas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        Home = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        header = new javax.swing.JPanel();
        tituloHeader = new javax.swing.JLabel();
        sectionInteration = new javax.swing.JPanel();
        pesquisa = new javax.swing.JTextField();
        novo = new javax.swing.JButton();
        busca = new javax.swing.JButton();
        filtro = new javax.swing.JComboBox<>();

        jComboBox1.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Título", "Tipo", "Ingrediente" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Organizador de Receitas");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Home"); // NOI18N

        Home.setBackground(new java.awt.Color(255, 255, 255));
        Home.setMinimumSize(new java.awt.Dimension(200, 200));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[] {
                        "Titulo", "Tipo", "", ""
                }) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 2 || column == 3;
            }
        });
        jScrollPane1.setViewportView(tabela);
        tabela.setRowHeight(32);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(2).setPreferredWidth(32);
            tabela.getColumnModel().getColumn(2).setMaxWidth(32);
            tabela.getColumnModel().getColumn(3).setMaxWidth(32);
            tabela.getColumnModel().getColumn(3).setPreferredWidth(32);

            // Double Click para visualização da Receita
            tabela.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    if (e.getClickCount() == 2) {
                        JTable target = (JTable) e.getSource();
                        String tituloReceitaSelecionada = String
                                .valueOf(target.getValueAt(tabela.getSelectedRow(), 0));
                        int receitaId = gerenciador.readReceitas().stream()
                                .filter(receita -> receita.getTitulo().equals(tituloReceitaSelecionada))
                                .collect(Collectors.toList()).get(0).getId();
                        new ApresentaReceita(receitaId).setVisible(true);
                    }
                }
            });

            // Botões das Colunas
            editar = new ButtonColumn(tabela, 2) {
                @Override
                public void actionPerformed(ActionEvent e) {
                    fireEditingStopped();
                    DefaultTableModel tabelaModel = (DefaultTableModel) tabela.getModel();
                    String tituloReceitaSelecionada = String
                            .valueOf(tabelaModel.getValueAt(tabela.getSelectedRow(), 0));
                    int receitaId = gerenciador.readReceitas().stream()
                            .filter(receita -> receita.getTitulo().equals(tituloReceitaSelecionada))
                            .collect(Collectors.toList()).get(0).getId();
                    new TelaNovaReceita(Project.this::updateTabelaReceitas, receitaId).setVisible(true);
                }
            };
            excluir = new ButtonColumn(tabela, 3) {
                @Override
                public void actionPerformed(ActionEvent e) {
                    fireEditingStopped();
                    DefaultTableModel tabelaModel = (DefaultTableModel) tabela.getModel();
                    String tituloReceitaSelecionada = String
                            .valueOf(tabelaModel.getValueAt(tabela.getSelectedRow(), 0));
                    int receitaId = gerenciador.readReceitas().stream()
                            .filter(receita -> receita.getTitulo().equals(tituloReceitaSelecionada))
                            .collect(Collectors.toList()).get(0).getId();
                    gerenciador.delete(receitaId);
                    gerenciador.salvarArmazenamento();
                    updateTabelaReceitas(gerenciador.readReceitas());
                }
            };
            editar.getRenderButton()
                    .setIcon(new javax.swing.ImageIcon("./src/resources/images/edit.png"));
            excluir.getRenderButton().setBackground(new Color(0xC80815));
            excluir.getRenderButton()
                    .setIcon(new javax.swing.ImageIcon("./src/resources/images/delete.png"));
        }

        header.setBackground(new java.awt.Color(204, 0, 255));

        tituloHeader.setBackground(new java.awt.Color(255, 255, 255));
        tituloHeader.setFont(new java.awt.Font("Nimbus Roman", 0, 24)); // NOI18N
        tituloHeader.setForeground(new java.awt.Color(255, 255, 255));
        tituloHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloHeader.setText("Organizador de Receita");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
                headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerLayout.createSequentialGroup()
                                .addComponent(tituloHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 630,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        headerLayout.setVerticalGroup(
                headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tituloHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE));

        sectionInteration.setBackground(new java.awt.Color(255, 255, 255));

        pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaActionPerformed();
            }
        });

        novo.setText("Novo");
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed();
            }
        });

        busca.setBackground(new java.awt.Color(204, 0, 255));
        busca.setIcon(new javax.swing.ImageIcon("./src/resources/images/big-search-len.png")); // NOI18N
        busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaActionPerformed();
            }
        });

        filtro.setModel(
                new javax.swing.DefaultComboBoxModel<>(
                        new String[] { "Buscar por título", "Buscar por tipo", "Buscar por ingrediente" }));

        javax.swing.GroupLayout sectionInterationLayout = new javax.swing.GroupLayout(sectionInteration);
        sectionInteration.setLayout(sectionInterationLayout);
        sectionInterationLayout.setHorizontalGroup(
                sectionInterationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sectionInterationLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(novo)
                                .addGap(8, 8, 8)
                                .addComponent(busca, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 269,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 148,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        sectionInterationLayout.setVerticalGroup(
                sectionInterationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sectionInterationLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(sectionInterationLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(sectionInterationLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(filtro, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(novo, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(busca, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)));

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
                homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(header, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addComponent(sectionInteration, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1));
        homeLayout.setVerticalGroup(
                homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(sectionInteration, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361,
                                        Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateTabelaReceitas(ArrayList<Receita> receitas) {
        DefaultTableModel tabelaReceitas = (DefaultTableModel) tabela.getModel();
        int i;
        for (i = tabelaReceitas.getRowCount() - 1; i >= 0; i--)
            tabelaReceitas.removeRow(i);
        for (i = 0; i < receitas.size(); i++)
            tabelaReceitas.addRow(new Object[] {
                    receitas.get(i).getTitulo(),
                    receitas.get(i).getTipo().getDescricao()
            });
    }

    private void novoActionPerformed() {// GEN-FIRST:event_novoActionPerformed
        new TelaNovaReceita(Project.this::updateTabelaReceitas).setVisible(true);
    }// GEN-LAST:event_novoActionPerformed

    private void pesquisaActionPerformed() {// GEN-FIRST:event_pesquisaActionPerformed
        switch (filtro.getSelectedIndex()) {
            case 0:
                updateTabelaReceitas(gerenciador.readReceitas(pesquisa.getText()));
                break;
            case 1:
                TipoReceita[] tipos = Arrays.stream(TipoReceita.values()).filter(
                        tipo -> gerenciador.verificarContemString(tipo.getDescricao(), pesquisa.getText()))
                        .toArray(size -> new TipoReceita[size]);
                updateTabelaReceitas(gerenciador.readReceitas(tipos));
                break;
            case 2:
                ArrayList<String> ingredientes = new ArrayList<>(
                        Arrays.asList(pesquisa.getText().split("[\\s,]+")));
                updateTabelaReceitas(gerenciador.readReceitas(ingredientes));
                break;
            default:
                break;
        }
    }// GEN-LAST:event_pesquisaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home;
    private javax.swing.JButton busca;
    private javax.swing.JComboBox<String> filtro;
    private javax.swing.JPanel header;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton novo;
    private javax.swing.JTextField pesquisa;
    private javax.swing.JPanel sectionInteration;
    private javax.swing.JTable tabela;
    private javax.swing.JLabel tituloHeader;
    private ButtonColumn editar;
    private ButtonColumn excluir;
    private Gerenciador gerenciador;
    // End of variables declaration//GEN-END:variables
}
